title: Home
description: My personal website
baseurl: ""  # kosong karena ini GitHub Pages utama
url: "https://nursitaaa.github.io"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
