title: Home
baseurl: "" # kalau di root, biarkan kosong
url: "https://nursitaaa.github.io/" # ganti sesuai username kamu

sass:
  style: compressed

theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag