title: Home
baseurl: ""  # Ganti sesuai nama repo kamu
url: https://nursitaaa.github.io/nursitaaa/


sass:
  style: compressed

theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
