title: Home
baseurl: "/nursitaaa"    # Sesuaikan dengan nama repo GitHub Pages-mu
url: https://nursitaaa.github.io

sass:
  sass_dir: assets/css
  style: compressed

theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
